name: Exercices/Example

on:
    pull_request:
        paths:
            - "commun/exercices/example/response/**"

jobs:
    evaluation:
        runs-on: ubuntu-latest
        steps:
            -   name: ğŸ“¦ Checkout project
                uses: actions/checkout@v3

            -   name: ğŸ— Installation
                working-directory: commun/exercices/example
                run: composer require phpunit/phpunit

            -   name: ğŸ“ Evaluate
                working-directory: commun/exercices/example
                run: vendor/bin/phpunit tests

            -   name: ğŸŠ Congratulation
                run: echo "Great job ğŸ‘Œ"
